### ISSUE TITLE
Add to Quicklisp?

### ISSUE THREAD

**Issue by mmontone** [szos/cl-advice#3]
Would you agree to adding this to Quicklisp?

**Comment by szos** [comment]
I tried responding by email but it doesn't look like it went through so I'm copy/pasting it below:

I would be fine with having this added to quicklisp. Its not super complex, and I don't plan on adding more features. I have only tested against SBCL, so testing against other implementations would be useful before adding it.

**Comment by mmontone** [comment]
Ok. Will test in other impletations. Perhaps could also add some Unit tests.

Yes this is a simple package, but useful to have easily available
nonetheless.

**Comment by szos** [comment]
Absolutely. Ill get a test suite written and added to the repo.

**Comment by mmontone** [comment]
Great. If you don't want to do it, I can do it :)

I was thinking of capturing output:

```lisp
(defpackage :advice-tests
  (:use :cl :cl-advice))

(in-package :advice-tests)

(defun foutput (fun)
  (with-output-to-string (*standard-output*)
    (funcall fun)))

(defun main ()
  (format t "main"))

(assert (string= (foutput 'main) "main"))

(defun before ()
  (format t "before"))

(cl-advice:make-advisable 'main)

(assert (string= (foutput 'main) "main"))

(cl-advice:add-advice :before 'main 'before)

(assert (string= (foutput 'main) "beforemain"))
```

Just an idea.

**Comment by szos** [comment]
That's definitely a way about it. I havent given it much thought yet, as its soon midnight for me, but my initial thought was to define a bunch of flags and set them in various bits of advice, finally checking to see if they're set.

**Comment by mmontone** [comment]
As you wish. I like it the way I described because the tests are independent of the implementation.

**Comment by mmontone** [comment]
Yes, your approach should be fine too.

**Comment by szos** [comment]
If you wish to write a test suite I'd gladly accept a PR for it.

**Comment by mmontone** [comment]
Sure. I could have it this weekend. Fiveam testsuite would be alright?

I would do it like I described, or setting flags as you suggested . But not a lot of code ..

**Comment by szos** [comment]
I'm fine with either approach. And yes, fiveam is preferred as its the only suite I'm familiar with.

**Comment by mmontone** [comment]
Ok. I can do it.

**Comment by szos** [comment]
Thanks! Open up a PR whenever you're ready.

**Comment by szos** [comment]
I would be fine with having this added to quicklisp. Its not super complex, and I don't plan on adding more features. I have only tested against SBCL, so testing against other implementations would be useful before adding it.

24. mar. 2022 22:01:14 Mariano Montone ***@***.***>:

**Comment by mmontone** [comment]
cl-advice is on Quicklisp already :)

**Comment by szos** [comment]
My apologies, i have no idea how that email got sent just now; I wrote and sent it back in march. I wonder if my email client is having issues or something... 

Anyway, disregard, and apologies for necroposting.
