### ISSUE TITLE
ensure-advisable-function

### ISSUE THREAD

**Issue by mmontone** [szos/cl-advice#5]
Hello again :)

Nothing of much importance, but I wonder about the design decision of making an explicit distinction between advisable and non-advisable functions. Why is it that you require a function to be defined or converted explicitly to advisable, and signal an error otherwise?

Let's say `ensure-adivisable-function`, instead of signal an error on unadvised functions,  converted the function to advisable if it is not already, on the fly. Then you could just install advice on any function, regardless of if that function was declared as advisable or not, and without an explicit conversion/declaration.

**Comment by szos** [comment]
I like that idea, it makes good sense. One thing I think of though is locked packages. for example, you cant change `#'cl:remove` to be advisable as it is within a locked package. However that could be easily addressed by installing a restart to abort changing the function to be advisable. Ill make some changes and push them in (after running the test suite, of course, and perhaps adding more tests.

**Comment by mmontone** [comment]
I think that would be great. Another point in favor of automatic conversion is when two libraries want to advice the same function. They don't need to manually check if the function is already advisable or not before applying their advices. Not likely to occur in practice perhaps (unless you are using that function as a "hook"), but I like the "automatic install" better anyway.

The parts that check for error signaling when adding advice on unadviced functions will need to be removed (in the tests, I  mean)

**Comment by mmontone** [comment]
And `defun-advisable` could be removed too.

**Comment by szos** [comment]
Noted. Another thing I wish to address is changing some of the forms from macros to functions, eg make-advisable, to allow them to be passed around as first class objects.

**Comment by szos** [comment]
Ive made some progress on how to change this to allow implicit conversion and would like your thoughts. What I'm thinking of doing is `signal`-ing a condition within `ensure-advisable-function` and installing restarts around it. If the signal is unhandled it will change the function to an advisable function, and if it is handled there will be two restarts available to explicitly allow or disallow conversion to an advisable function. A rough sketch is: 

```lisp
(defun ensure-advisable-function (symbol &optional arguments force-use-arguments)
  (check-type symbol (or symbol function))
  (let ((fn (if (symbolp symbol)
                (symbol-function symbol)
                symbol)))
    (if (advisable-function-p fn)
        fn
        (progn
          (restart-case (signal 'implicit-conversion-to-advisable-function
                                :function symbol)
            (allow-conversion ()
              nil)
            (disallow-conversion (action)
              (return-from ensure-advisable-function
                (funcall action))))
          (make-advisable symbol
                          :arguments arguments
                          :force-use-arguments force-use-arguments)
          fn))))
```

This would allow using `handler-bind` to prevent conversion if desired, which could then be wrapped up in a macro like `(with-implicit-conversion-to-advisable-function ([:allowed|:disallowed]) ...body...)`. What are your thoughts on such a system?

**Comment by mmontone** [comment]
I like it. More control to the user. And I like that the default is to convert to advisable.

**Comment by szos** [comment]
Another idea ive been throwing around is having the function `ensure-advisable-function` be itself an advisable function, and providing a set of macros `with-temporary-advice` to bind and then restore a functions advice slots. This could then be used to control whether a function gets automatically converted to advisable or not.

**Comment by mmontone** [comment]
Ok. I lean on more on the automatic side of things. Like it is in Emacs. I don't see the user minding too much about if some function is advisable or not. As long as it does not get too complicated, I would be fine with it.

**Comment by szos** [comment]
Ill play around with both methods a little more and see which feels best. I agree about automatic conversion being the default though.

**Comment by mmontone** [comment]
How about a toggleable global variable to control if you want automatic conversion or not?

(I don't mind too much as long as I can make it work automatic somehow :smile: )

**Comment by szos** [comment]
automatic will definitely be the default. Im not opposed to a global variable, but I tend to avoid them. I've got to head towards sleep, Ill play with these ideas tomorrow and get back to you.

**Comment by szos** [comment]
I think I've found a good solution, would you mind checking out the branch https://github.com/szos/cl-advice/tree/functionalize-and-general-fixes and letting me know what you think?

**Comment by mmontone** [comment]
I have no complaints :smile: 

A detail: add `(make-unadvisable 'values-main)` at the end of the `advice-multiple-values` test, as a clean-up, so that tests can be run multiple times without failing.
